### PR TITLE
Additional collections, PW

### PR DESCRIPTION
**Pull request by Shinsina**
Smart Packaging: https://manage.pmmimediagroup.com/browse/?sort.field=PUBLISHED&taxonomyIds=2008434
Screenshot from 2024-02-07 08-33-38

Case Studies (Cartoning): https://manage.pmmimediagroup.com/browse/?sort.field=PUBLISHED&labels=Case%20Study&taxonomyIds=2008383
Screenshot from 2024-02-07 08-34-06

Case Studies (Coding/Marking): https://manage.pmmimediagroup.com/browse/?sort.field=PUBLISHED&labels=Case%20Study&taxonomyIds=2008344
Screenshot from 2024-02-07 08-34-30

Case Studies (Palletizing): https://manage.pmmimediagroup.com/browse/?sort.field=PUBLISHED&labels=Case%20Study&taxonomyIds=2008399
Screenshot from 2024-02-07 08-34-42

### CODE REVIEW

**Comment by Shinsina** [comment]
[Create Collections Page: Smart Packaging](https://trello.com/c/7dQF2boH/793-create-collections-page-smart-packaging)

**Comment by Shinsina** [comment]
[Create Case Studies Collection Page: Palletizing Equipment](https://trello.com/c/PbWBOhPO/791-create-case-studies-collection-page-palletizing-equipment)

**Comment by Shinsina** [comment]
[Create Case Studies Collection Page: Cartoning Equipment](https://trello.com/c/n6Zb0gh4/792-create-case-studies-collection-page-cartoning-equipment)

**Comment by Shinsina** [comment]
[Create Case Studies Collection Page: Coding/Marking](https://trello.com/c/nHgWiztl/794-create-case-studies-collection-page-coding-marking)

**Review by jwade1327 — APPROVED** [review]

**Pull request merged**
