### PR TITLE
Update PMMI Search Pages to use marko-web-search package.

### PR DESCRIPTION
**Pull request by Shinsina**
Shoutout @B77Mills https://github.com/parameter1/pmmi-media-group-websites/pull/242

Screen Shot 2021-11-16 at 2 33 18 PM
Screen Shot 2021-11-16 at 2 34 38 PM
Screen Shot 2021-11-16 at 2 35 58 PM
Screen Shot 2021-11-16 at 2 38 58 PM
Screen Shot 2021-11-16 at 2 40 31 PM
Screen Shot 2021-11-16 at 2 40 41 PM

### CODE REVIEW

**Comment by Shinsina** [comment]
[PW: Content types and website sections for new search page](https://trello.com/c/pmcgy9ZV/112-pw-content-types-and-website-sections-for-new-search-page)

**Comment by Shinsina** [comment]
[AW: Content types and website sections for new search page](https://trello.com/c/mHSm9yp8/113-aw-content-types-and-website-sections-for-new-search-page)

**Comment by Shinsina** [comment]
[PFW: Content types and website sections for new search page](https://trello.com/c/6I0szn1J/117-pfw-content-types-and-website-sections-for-new-search-page)

**Comment by Shinsina** [comment]
[OEM: Content types and website sections for new search page](https://trello.com/c/iJtNNmIW/116-oem-content-types-and-website-sections-for-new-search-page)

**Comment by Shinsina** [comment]
[HCP: Content types and website sections for new search page](https://trello.com/c/fhNiDgMh/114-hcp-content-types-and-website-sections-for-new-search-page)

**Comment by Shinsina** [comment]
[MUNDO: Content types and website sections for new search page](https://trello.com/c/6mHLR65g/115-mundo-content-types-and-website-sections-for-new-search-page)

**Review by brandonbk — APPROVED** [review]

**Pull request merged**
